# Generated by Django 5.1.7 on 2025-03-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Account_Id',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Transaction_Id',
            new_name='transaction_id',
        ),
    ]
